version: '3.4'

services:
  catalog.db:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.Api/Dockerfile
  
  basket.db:
    image: redis

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket/Basket.Api/Dockerfile

volumes:
  mongo_data:
  redis_data: