version: '3.4'

services:
  catalog.db:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CATALOG_DB_CONN_STRING=mongodb://catalog.db:27017"
    depends_on:
      - catalog.db
    ports:
      - "8000:80"

  basket.db:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "BASKET_DB_CONN_STRING=basket.db:6379"
    depends_on:
      - basket.db
    ports:
      - "8001:80"
